module.exports.cities = [
  'London',
  'Birmingham',
  'Manchester',
  'Leeds',
  'Newcastle',
  'Birstall',
  'Glasgow',
  'Liverpool',
  'Portsmouth',
  'Southampton',
  'Nottingham',
  'Bristol',
  'Sheffield',
  'Kingston upon Hull',
  'Leicester',
  'Edinburgh',
  'Caerdydd',
];